version: 1.0.0
Logging:
    stdout: false
    level: debug
    path: applog.log
server:
    port: ':8080'
mongodb:
    uri: "mongodb+srv://Node:Aman%40301@atlascluster.ys5i7lm.mongodb.net/ginDB?retryWrites=true&w=majority&appName=AtlasCluster"